services:
  m347-kn04a-web:
    build: 
      context: .
      dockerfile: php.dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - m347-kn04a-db
    networks: 
      - kn04a_net

  m347-kn04a-db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kn04a_net

volumes:
  db_data:

networks:
  kn04a_net:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
          ip_range: 172.10.5.0/24
          gateway: 172.10.5.254
