version: '1'

services:
  php:
    build: 
      context: .
      dockerfile: php.dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
